### PR TITLE
Livereload fixes / enhancements

### PR DESCRIPTION
**Pull request by theogravity**
This update fixes issues with using `livereload` where the RSG page refreshes but updates do not show up without a manual refresh:

- Move the creation of the react-docgen props output to a separate file for performance
- Move the generation of the index.html file as the last phase for a livereload watcher to watch for to refresh the server
- Add livereload embed option (so one does not have to use a flaky chrome/firefox livereload extension)
- Fix issue where the error log for duplicate display names were not being triggered properly
- Removed duplicate error logs

### CODE REVIEW

**Comment by marcello3d** [comment]
I think it'd be better to pull the livereload.js from node_modules rather than including in this git repo.

**Comment by theogravity** [comment]
@pocotan001 Can you review? I've integrated latest changes from master.

**Comment by theogravity** [comment]
Unsure why it's not installing `standard` on the CI

**Comment by theogravity** [comment]
have an updated pr using webpack and a major refactor

**Pull request closed without merging**
